### ISSUE TITLE
Cache和Queue分开数据库

### ISSUE THREAD

**Issue by hardywen** [TargetLiu/PHPRedis#1]
现在组件貌似不支持 分开配置Cache和Queue用的数据库，比如Cache我想用redis的数据库1,而Queue我想用redis的数据库2. 

能支持一下吗？

**Comment by TargetLiu** [comment]
恩 目前还不支持分开哈   我周末抽时间弄一下~~

**Comment by hardywen** [comment]
好的，期待  :)

**Comment by TargetLiu** [comment]
已经修改支持不同的链接了哈~~~

**Comment by hardywen** [comment]
coooool
