### ISSUE TITLE
pconnect 的问题

### ISSUE THREAD

**Issue by hardywen** [TargetLiu/PHPRedis#2]
https://github.com/TargetLiu/PHPRedis/blob/master/src/Database.php#L67

这里用了 pconnect . 导致了偶尔会得不到数据（应该是pconnect没有重新开一个链接，而是使用上一次链接的原因，使用上一次的链接并不是我真正想要的，所以拿不到数据了）

我把这里改成 connect 就没有问题了。能否抽空修改一下呢？
ps: 改成connect虽然把问题解决了。但性能绝对是比不上pconnect了。不知道有没有其他解决方案

**Comment by TargetLiu** [comment]
[http://blog.csdn.net/qmhball/article/details/46988111](http://blog.csdn.net/qmhball/article/details/46988111)

pconnect 的链接周期是一个fpm进程的生命周期

你具体的业务情况是什么样的呢？为什么不需要保持长链接呢？

**Comment by hardywen** [comment]
应该是配置了php-fpm原因，一个fpm进程会服务多个请求. 具体原因我还是不太确定。
业务上：
一个请求，会使用到 app('phpredis') ，cache, queue  这三个。 然后我为这三个都配置了不同的库，分别是1，2，3.

**Comment by TargetLiu** [comment]
可能是由于同一个redis，不同库使用同一个连接造成的。

现在已经改成同一个redis，不同库也使用不同的连接。你再试试呢？

**Comment by hardywen** [comment]
更新了，试了一下，貌似没什么问题了 :)

**Comment by TargetLiu** [comment]
好的，如果还有问题欢迎反馈，谢谢支持
